---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./tautulli/ks.yaml
  - ./plex/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  # - ./lidarr/ks.yaml
  # - ./prowlarr/ks.yaml
  # - ./overseerr/ks.yaml
  # - ./recyclarr/ks.yaml
  # - plex-meta-manager
  # # - ./jellyfin/ks.yaml
