---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./thanos/ks.yaml
  - ./grafana/ks.yaml
  - ./loki/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./unpoller/ks.yaml
  - ./node-problem-detector/ks.yaml
  - ./karma/ks.yaml
  # - blackbox-exporter
  - ./smartctl-exporter/ks.yaml
  - ./vector/ks.yaml
  - ./gatus/ks.yaml
  - ./teslamate/ks.yaml
