---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
  # - snapshot-cronjob-controller.yaml
  # - apply-ingress-auth-annotations.yaml
  - apply-ingress-external-dns-annotations.yaml
  - sync-postgres-secrets.yaml
