---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - blog
  - ./littlelinks/ks.yaml
  # - excalidraw
  - ./weave-gitops/ks.yaml
  - ./paperless/ks.yaml
  - ./hajimari/ks.yaml
  - ./shlink/ks.yaml
  - ./miniflux/ks.yaml
  - ./atuin/ks.yaml
  - ./kromgo/ks.yaml
