# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:GZ/ML2cjd/YddL8s+uuaZQfJou9YSJ0IP/Et0XozscUXHFysJtZWc7mQb/V0LqPu79ZNDf+U8BKAakachQaaHpZC5TEObwaB44IsYo4rtZ/GU0mGxOjNfMb21ma/x+7YcFwPqvx9meJ3Q0eRDDDLV97g/AXGbebzgtzknq3Vn3HCym0Qd91R/W2tSVUB37WTwi4iHYwEDq53PYxIpnijDiI+QHmBuaj9XK99wvdw0z+oPkxb1Y56Zj+R3vIbAPKZPO72xhRder0KjAK97NfZJ+WG1OxEsG2tDQcbByBS5NorkWmHYichK+adJIpowUjKRpxxTI94OWWA58rfR/tYoQwWbNzoPDTKdlYpza5Wc3Gjf7IYLwoC32gY2hdYFLufHYFE5pCqDOXUkaJk98DvtCq2BsT04qXSljyNwU4aZwRqmfT0uCMZp915oMV95maZBIs9BWCWg6i6h41OVo331XU9pR3zBzs3jy6DW40sFrJuFEhLWl/s5FglAEfWdGw3/D6yydM+LbF7c6QCaZRX9F1/2gLztbZr5cqSifAh9SHaxu7zmoizrIt9JHv8L2Tl+A+g7J2bcqhhtuatOMGDkm14aIOVJByJ0HFwm77nnZaxE8xbSZCylEng9Ovatd1BbbnnAsraB468io3lHbO/8sGDjfKVNItaYXY6kiBNLWy54bygOBNomItsRawncvsmrGopUNyM8WpkxO0hYZUR8zkDohS/IlUzJEYGiFIVbdauUOjPwinQePmhtKwhiq6R5bRdITQ/j/EDpdi/9h0MIfMcMCTQEomHnsiDrAfIBKb0fuXlNviw9OFikGUUBgTMiEJlkpD7xEdNY9uPiVXaijqMBtOkk+hYiyuBBGNKVuAbjTiphw4gG3gMd+Iq5UNLfdV5peDGL+f9TTqDC0ylA0c/EjJkGTLnMJZGZ0grKksPDoX1aXzTLam3FfqeymEze8nj2G0FRMJIuTcJ+n1DDyxUlfPTpZ3/coqzl2TSyEtZz4QsqnwffU2SSCmKYfVlotExsFFiUgwcQNkWv9RBvadxk4sElLJHe18paUABl9Hla7m3tsNh4WPS/XBEWNhAfyMXrA3XvwVy+pTKtezNDtpB6e9mGIaUi557aViLTbDn3OlFucuN4In7LZYBl/9l6VKHWRaxzDKT+C9DsayR6zreg3ykAIoD2DiBzN9cd8wfWnDfH6ZSa1T4/eqvouVxPX52nszdPWGH1jziddlaynnqA5igq13L2L+qjzn2ImxYroZFJR0AXTPQqe8E0WCbwTG477I5IWX9irZmPBpg/S4bArrWkJMjjwYVC5TpDrA1inQUtDawwC6XViOCw82GzsjCtOk/jfV1dENJ478SmySMXOR/AK3ped2EH+lJKOJt09CNbZUxwgvs5FgOrzSLmPhXABQPfGaKdwp1j3SDU/RP2uEPiuf4+ZdtGYi7TkhWr0FeeWkhkd2Xdj3s/C3acahhgMTFYnw7J+Krgp1N2U11heHXW0xAUk0HVidI/E36YGfz/6tQHQkIPK9BQ3BbGoRCRZZy/TkaTjm7dhOwN97U1sdMOhDgfBFslWLa6AEEEURQxGhWkhd1caFhS4CC9exxi6+y/9y2tQDNQXFg6bBekw80GiQe5CVhJuGDqlQC4ZMT5o0w9q0l97uozIu9heaj3KqNGbPQTf/0POdCVZjAun+fg0llCW7tMt5R/zTCPke0K5mz71DN50RZGc+Q3B4f1DdNE93aLh5DGMnOpx0NK8otPU9q+yQu29UAOxxxyC+yq8+bl+Zmme8TvZ6hc3o3dzGmk0UBRTBFpb6kWKDuPh+mytBHa83QsK7TJM1fcaKPb33kBoteYjal5JI8OXTXTf7Zp0rtHuljPk94HUOiFQBTH4LZU4x4/8tpfZaxncGyiv33sULbwI2NE3Yg8M40XJDjTQF8wWzfTsTFk1h4h4Fpa+ffmawOUm7T,iv:ZVIsRmCl9O1K8xA5EBZCnc978uJNA1gjxQ5UMV+5NSw=,tag:jVa2qZpqmBWRPAWCaCOQXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOG5lcXdicUdxTEdHaEEw
            Vm1WUUQraG1zT3ltYmJ1WjFzVkltSlcybVhRCkFybzFkTHNWRlV4VDRqb2hVSGFK
            ZzFUUjUybVN2MjZocHNPK1VUV0FUSFEKLS0tIFBhTXN4R1BUK0NkU1pZSFhmekFq
            M0JuQ0hJc3pMZGVoV1ZRdFNUdFpIdTQKmYhm7voKI2hfEbrtuYV5vKqXkKUNXg5s
            MX6TE3tfBjajia/OrVkywKPQd9nke1q4kkUb1lrp6wWmb6pfSB8kUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T15:29:04Z"
    mac: ENC[AES256_GCM,data:vZExjhIpbpeSeFHvNC8eM8fmp9HMZeh8ZHJXpyqz7EiVL95Us5OVeo0+uVlbk2cbEMVoq0ZnakWpqYn1CDZGAMSsvIZrzsEfWuJ42vfDPGB0QtfAD3NlBbInA+SUt8zifAazwfAKW5FfUj1AbLDu50noRSZPxfS+fzF+3dUGRcw=,iv:ohICOktH4cT5gheUxOI79wwtW+aKQwLIzjPBwGLzP00=,tag:GfeCpgUZYOgIZN8rS5txwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:mUeZxYYMswoqCd8WhLLQzMOyQ+OODJpcI/Tk2wNbuwjoWR5QhrEWAhmKr0y1HtEA7/7sC5k70DoH2cs4NBkMF4faLe3Zi3MAeO3Nqd87NiHO0FQoepVXu0RDSWmdtFtUGbsnwvsdBJpl40GOvoSqPzBHfDA1YNiRYpqbAYwQoOzJqcHFgzK/nvuQagr92Yq9PtWcdpqpbPybxjMh3qwp/4TijeSiWc6cPBB27T93N8d5PMiZ/U5q89qth03uILGOcI9Zw9NyGuYI1wgeTlNKOq423A+CRd3ZM29EgZIPAF7k8GqUxqvu2+iRpQ5CBYlNFPJyol4OJluyPZEXFQBFwh23Tf66kQY2kUOServLkzq4PufiGzDp/XYzFWaUQOXM2UVzvu8mKasFC/C2v1297htOj565gOzS/go8aSubP2duWYpbzdHafz48SiwQgz5ExaDbpJ55M0xU3wlhHV3FVEVlPMmZK4JqmoHIiaZAGZpHokovjIBt5r8XE9cZ9e16Rq2GppL6R3iK1qLsVAxZOwHHHUYZ6Xkutv7l4q/8xot6QOmAfpDkBd3TqIqylT8QffP7MqMLSeeIyUVI7YhlxsqUlE08+mRLdO1TBCupeCj223s6AXzYUj1dIej/270Ve/i4DYLoJJh2bswUscrlJMufGu8fYx+DX/mGSW3MsKdF6Rw/G4aDVydBCvvRKLz86UM87bRUMTcHmWXSi2ZYhbEousLtDscbjCxwBy7a0Oka5UNr9tXmjL5pSnZQPpqeFYCORACy+NJbTRFGk/ZVIjKIXYVut96BMwLHiKAacACcP8vO9VlAcmzIP7BINh6WuWT952cNIqn9nKH1kaREXvPR,iv:prXjYSS7Yau0MSfXcGqw0DfU1j7HAxPXuyLhvGwvoOc=,tag:obbIcNApONnFnppp4FiHKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOG5lcXdicUdxTEdHaEEw
            Vm1WUUQraG1zT3ltYmJ1WjFzVkltSlcybVhRCkFybzFkTHNWRlV4VDRqb2hVSGFK
            ZzFUUjUybVN2MjZocHNPK1VUV0FUSFEKLS0tIFBhTXN4R1BUK0NkU1pZSFhmekFq
            M0JuQ0hJc3pMZGVoV1ZRdFNUdFpIdTQKmYhm7voKI2hfEbrtuYV5vKqXkKUNXg5s
            MX6TE3tfBjajia/OrVkywKPQd9nke1q4kkUb1lrp6wWmb6pfSB8kUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T15:29:04Z"
    mac: ENC[AES256_GCM,data:vZExjhIpbpeSeFHvNC8eM8fmp9HMZeh8ZHJXpyqz7EiVL95Us5OVeo0+uVlbk2cbEMVoq0ZnakWpqYn1CDZGAMSsvIZrzsEfWuJ42vfDPGB0QtfAD3NlBbInA+SUt8zifAazwfAKW5FfUj1AbLDu50noRSZPxfS+fzF+3dUGRcw=,iv:ohICOktH4cT5gheUxOI79wwtW+aKQwLIzjPBwGLzP00=,tag:GfeCpgUZYOgIZN8rS5txwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
