---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: synology-nas
spec:
  staticConfigs:
    - targets: ["192.168.0.18"]  # Updated to match the static_configs.targets in your Prometheus config
  metricsPath: /snmp
  params:
    module: [synology]  # Specifying the module as in your Prometheus job config
  relabelings:  # Adjusted to 'relabelings' to match typical CRD field names, might need adjustment based on your actual CRD
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: "192.168.0.18:9116"  # Replacement to match the SNMP exporter's service address
